### ISSUE TITLE
GPU missing when mining over rdp

### ISSUE THREAD

**Issue by ghost** [cbuchner1/CudaMiner#102]
When starting up miner over remote desktop I get this error message:

Unable to query CUDA driver version! Is an nVidia driver installed?

 Using Win8.1 x64

Cheers.

**Comment by cbuchner1** [comment]
remote desktop prevents applications from accessing OpenGL and CUDA
directly, as they run under some virtual desktop environment.

I would recommend to use VNC for remote logins instead.

2014-02-18 9:13 GMT+01:00 Tuomas Soikkeli notifications@github.com:

**Comment by ghost** [comment]
Seems to be native windows problem than software.

**Comment by whitesand77** [comment]
TeamViewer has a better "windows" experience than VNC.
