### ISSUE TITLE
GPU #0: cudaError 30 (unknown error) calling 'result = cudaStreamSynchronize(stream)' (salsa_kernel.cu line 902)

### ISSUE THREAD

**Issue by justnx** [cbuchner1/CudaMiner#104]
Getting: GPU #0: cudaError 30 (unknown error) calling 'result = cudaStreamSynchronize(stream)' (salsa_kernel.cu line 902)
after some time running CudaMiner with GTX 750 Ti

**Comment by cbuchner1** [comment]
I suspect that your overclock is a bit too extreme.

2014-02-23 10:22 GMT+01:00 Julian Sternberg notifications@github.com:

**Comment by justnx** [comment]
My card is not overclocked at all. 
It's an EVGA 750 Ti (no superclocked) 
running on Debian Wheezy x64 with NVIDIA-Linux-x86_64-331.49 driver and cuda-linux64-rel-5.5.22-16488124

**Comment by cbuchner1** [comment]
but pressing CTRL-C and restarting cudaminer will then work again, for a
while?

I've had one guy report an unknown error after some time which he required
a reboot to recover.

Christian

2014-02-23 10:46 GMT+01:00 Julian Sternberg notifications@github.com:

**Comment by justnx** [comment]
Yes but just for some minutes. on keccak algo its crashing even faster

**Comment by cbuchner1** [comment]
this is likely some kind of hardware related problem. Does your BIOS offer
some options to change PCIe bus settings? e.g. dropping from Gen3 to Gen2.

Also maybe try the 314 beta driver that nVidia offers for Linux.

Christian

2014-02-23 11:11 GMT+01:00 Julian Sternberg notifications@github.com:

**Comment by justnx** [comment]
Good news Christian. 
Driver: http://us.download.nvidia.com/XFree86/Linux-x86_64/334.16/NVIDIA-Linux-x86_64-334.16.run
and setting PCI-E Slot to GEN 2 made it ;-)
