### ISSUE TITLE
Ubuntu 14.04 Pointer Issue

### ISSUE THREAD

**Issue by webbrandon** [cbuchner1/CudaMiner#112]
Hello,

I am compiling for a Ubuntu 14.04 x64 system with the 331.38 NVidia Driver for a GeForce GTX 670 card.  I am using the new driver support for NVIDIA (System Settings > Software Settings > Additional Drivers) and the new `sudo apt-get install nvidia-cuda-toolkit` availability.  The cuda package installs to `/usr/lib/nvidia-cuda-toolkit` instead of the normal `/usr/local/cuda`.  

How can I point this for CudaMiner to compile correctly?  Currently I get this:
`/usr/local/cuda/bin/nvcc -O3 -Xptxas "-abi=no -v" -arch=compute_10 --maxrregcount=64 --ptxas-options=-v -I./compat/jansson -o sha256.o -c sha256.cu
/bin/bash: /usr/local/cuda/bin/nvcc: No such file or directory
make[2]: *** [salsa_kernel.o] Error 127`

**Comment by SteveGotthardt** [comment]
Try this in directory with the cudaminer source:
make clean
./autogen.sh
./configure --with-cuda=/usr/lib/nvidia-cuda/toolkit
make
(and optionally: sudo make install)

**Comment by SteveGotthardt** [comment]
Sorry, dash instead of slash (or point it to where cuda is on your install)
./configure --with-cuda=/usr/lib/nvidia-cuda-toolkit

**Comment by webbrandon** [comment]
It compiled, thank you.  I will write a tutorial for 14.04 on askubuntu.com and reference here later.

**Comment by webbrandon** [comment]
BTW not a optimal setup I am only getting 170 khash/s average compared to build made from sources of 280 khash/s average.
