### ISSUE TITLE
Compile error with direction on fix

### ISSUE THREAD

**Issue by lightningjim** [cbuchner1/CudaMiner#115]
I did run autogen and compile before running make and go this error

g++  -g -O2 -pthread -L/usr/local/cuda-5.5/lib64  -o cudaminer cudaminer-cpu-miner.o cudaminer-util.o wrapnvml.o cudaminer-sha2.o cudaminer-scrypt.o cudaminer-maxcoin.o cudaminer-blakecoin.o cudaminer-sha3.o cudaminer-scrypt-jane.o salsa_kernel.o sha256.o keccak.o blake.o cudaminer-blake.o fermi_kernel.o kepler_kernel.o test_kernel.o nv_kernel.o nv_kernel2.o titan_kernel.o -L/usr/lib/x86_64-linux-gnu -lcurl -ljansson -lpthread  -lcudart -fopenmp -lcrypto -lssl  -lcrypto -lssl 
/usr/bin/ld: wrapnvml.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib/x86_64-linux-gnu/libdl.so.2 so try adding it to the linker command line
/lib/x86_64-linux-gnu/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

Added "-ldl" to the cudaminer_LDADD variable made it work just fine. It's appears to be a new requirement for Ubuntu 13.04 which isn't necssary for previous. However I have no idea if it's a bad idea for other variations to just "-ldl" in for them or if it'd cause issues as well.

**Comment by crnkoj** [comment]
Thanks for the tip, had the same issue on gentoo as well.  Just to add one  thing, the file that needs editing after doing autogen and configure is the Makefile.

**Comment by zeroedout** [comment]
Arch Linux user here, me too. Adding -ldl to the variable in Makefile worked. I'm assuming this is a general Linux problem atm? IIRC -ldl tells it to use LDFLAGS_LINUX so that does make sense...

**Comment by iGeorgeX** [comment]
Same problem for Fedora 20, -ldl fixed the problem.

**Comment by clubbby** [comment]
Thanks, worked here too. Ubuntu 13.10.

**Comment by lightningjim** [comment]
I've updated my git and found -ldl is now there automatically, so this looks resolved.
