### ISSUE TITLE
Reconnect on stratum protocol error

### ISSUE THREAD

**Issue by mibe** [cbuchner1/CudaMiner#12]
A couple of days ago I had a problem with cudaminer. After this line it stopped working completely:

"stratum_recv_line failed to parse a newline-terminated string"

Looks like some sort of protocol error of the pool communication to me. Anyway, it would be nice if on this sort of error cudaminer automatically reconnects to the pool instead of ceasing to mine.

**Comment by cbuchner1** [comment]
I think the root cause has been determined. I am in discussion with pooler,
the author of cpuminer (from which cudaminer is derived) whether to fix the
problem there.

2013/10/22 Michael Bemmerl notifications@github.com
