### ISSUE TITLE
K192x3 is faster than T192x1 or 2 on GTX780 3GB

### ISSUE THREAD

**Issue by albal** [cbuchner1/CudaMiner#13]
Hello,

Maybe I am not understanding correctly but with 2D cache in interactive mode I am getting 265KH/s using K192x3 @ 70% Use.  With T192x1 I am getting only 200KH/s, with T192x2 245KH/s, T192x3 then drops down to 

Asus OCII GTX780 OCed to 1306/6610

auto tuning results in T99x1 at 105KH/s

Cheers,
Al

**Comment by cbuchner1** [comment]
Try again with a later version. I've optimized the Tesla kernels a lot.

**Comment by albal** [comment]
Sorry didn't have chance to check this.  Anyway I pay for my own electric
so mining on Nvidia isn't feasible for me.

All the best,
Al
