### ISSUE TITLE
Unable to query CUDA driver version! error on Ubuntu 14.04, Nvidia driver 337.12

### ISSUE THREAD

**Issue by apemax** [cbuchner1/CudaMiner#133]
Hey. I've downloaded the latest cudaminer code from here but when I try to run in I get this error:

/usr/bin/nvidia-modprobe: unrecognized option: "-u"

ERROR: Invalid commandline, please run `/usr/bin/nvidia-modprobe --help` for usage information.

[2014-04-18 19:07:48] Unable to query CUDA driver version! Is an nVidia driver installed?

I just upgraded to Ubuntu 14.04 and Nvidia driver 337.12. Any ideas what could be going on here?

**Comment by NNygren** [comment]
Run with sudo

**Comment by apemax** [comment]
Running with sudo doesn't help. I think however this is a issue with my system and not CudaMiner so this can be closed now.

**Comment by utahman** [comment]
You didn't use any remote desktop view app to access your system? Some such apps prevent access to GPUs.

**Comment by apemax** [comment]
Nope. Odd thing is blender doesn't see the card either. I have a feeling there is something I'm missing that is really obvious but I can't think of why it's started doing this.

**Comment by utahman** [comment]
Try another card? To rule out mechanical problem
