### ISSUE TITLE
cudaminer can't detect/restart when video card driver crashes

### ISSUE THREAD

**Issue by drazisil** [cbuchner1/CudaMiner#138]
Instead it loops forever with 

GPU #0: cudaError 30 (unknown error) calling 'cudaStreamQu
ery(context_streams[stream][thr_id])' (D:/Christian/Documents/Visual Studio 2010
/Projects/CudaMiner/salsa_kernel.cu line 958)

**Comment by sephtin** [comment]
See the previously closed issues:
https://github.com/cbuchner1/CudaMiner/issues/109  and   https://github.com/cbuchner1/CudaMiner/issues/104

It happens when driver crashes.  Possible work-arounds are to try limiting PCIE slot to x2, and lowering clocks (if you're overclocked)...

I have lowered my overclock to the point where it only does this ~once a week.  I get an alert, and I remote to the system and stop and re-start cudaminer.

HTH

**Comment by drazisil** [comment]
is there no way for it to detect and restart on its own?
- Joseph Becher

**Comment by drazisil** [comment]
Also, I'm not overclocking it and I don't know what "limiting PCIE slot to x2" means. My real questions is, is there was way to change the code for it to detect a driver crash and recover? Or quit so I can restart via batch?

**Comment by sephtin** [comment]
If you figure it out, let me know too! (and the others from the other closed issues I linked).  :)

**Comment by drazisil** [comment]
Well, the failure line doesn't seam to match up with the source code, so I'm trying to build from scratch. I did find https://www.youtube.com/watch?v=8NtHDkUoN98 though, which may remove the need to even care, at least on windows. I'm still fighting with getting the project built though.

**Comment by drazisil** [comment]
I've zero luck building this, sadly

With http://support.microsoft.com/kb/2665946 my driver no longer crashes.

However, cudaminer now crashes on the following error.

[2014-05-22 14:33:41] GPU #0: cudaError 30 (unknown error) calling 'cudaStreamSy
nchronize(context_streams[1][thr_id])' (D:/Christian/Documents/Visual Studio 201
0/Projects/CudaMiner/salsa_kernel.cu line 224)

That's this command:  cudaDeviceReset();, which leads me to believe the driver may still be hanging.

I'm not really sure how to troubleshoot error 30, but hopefully this helps?
Running driver 337.50 with a GTX 660 under win 8.1

**Comment by drazisil** [comment]
Closing this out of my list
