### ISSUE TITLE
2013-11-01 compile error 

### ISSUE THREAD

**Issue by brianhenson** [cbuchner1/CudaMiner#14]
When trying to compile 2013-11-01 on Ubuntu 12.04. I get the following error and it will not proceed. configure: error: cannot run /bin/bash ./config.sub.

**Comment by adlerweb** [comment]
Files are encoded using windows line endings - you can use dos2unix to convert all files, compiled fine for me afterwards. Afair something like this should work:

  `for i in `find ./ -type f` ; do dos2unix "$i" ;done`

**Comment by brianhenson** [comment]
let me try it and see how it works. thanks for the tip

**Comment by brianhenson** [comment]
thanks that got rid of that error. compiling now
