### ISSUE TITLE
salsa_kernel.cu(691): error: identifier "checkCudaErrors" is undefined

### ISSUE THREAD

**Issue by einyx** [cbuchner1/CudaMiner#15]
Get this during the make step:

titan_kernel.h(6): error: not a class or struct name

spinlock_kernel.h(6): error: not a class or struct name

fermi_kernel.h(6): error: not a class or struct name

legacy_kernel.h(6): error: not a class or struct name

salsa_kernel.cu(43): error: identifier "KernelInterface" is undefined

salsa_kernel.cu(85): error: identifier "KernelInterface" is undefined

salsa_kernel.cu(93): error: identifier "KernelInterface" is undefined

salsa_kernel.cu(97): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(120): error: identifier "KernelInterface" is undefined

salsa_kernel.cu(120): error: identifier "kernel" is undefined

salsa_kernel.cu(122): error: identifier "WU_PER_LAUNCH" is undefined

salsa_kernel.cu(126): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(160): error: identifier "WU_PER_LAUNCH" is undefined

salsa_kernel.cu(217): error: identifier "KernelInterface" is undefined

salsa_kernel.cu(268): error: identifier "SCRATCH" is undefined

salsa_kernel.cu(268): error: identifier "WU_PER_WARP" is undefined

salsa_kernel.cu(270): error: expression must have pointer-to-class type

salsa_kernel.cu(283): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(294): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(307): error: expression must have pointer-to-class type

salsa_kernel.cu(308): error: expression must have pointer-to-class type

salsa_kernel.cu(310): error: expression must have pointer-to-class type

salsa_kernel.cu(315): error: expression must have pointer-to-class type

salsa_kernel.cu(316): error: expression must have pointer-to-class type

salsa_kernel.cu(318): error: expression must have pointer-to-class type

salsa_kernel.cu(334): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(349): error: expression must have pointer-to-class type

salsa_kernel.cu(368): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(392): error: expression must have pointer-to-class type

salsa_kernel.cu(398): error: identifier "WU_PER_LAUNCH" is undefined

salsa_kernel.cu(398): error: identifier "WU_PER_BLOCK" is undefined

salsa_kernel.cu(410): error: expression must have pointer-to-class type

salsa_kernel.cu(438): error: expression must have pointer-to-class type

salsa_kernel.cu(446): error: expression must have pointer-to-class type

salsa_kernel.cu(449): error: expression must have pointer-to-class type

salsa_kernel.cu(451): error: expression must have pointer-to-class type

salsa_kernel.cu(467): error: expression must have pointer-to-class type

salsa_kernel.cu(560): error: expression must have pointer-to-class type

salsa_kernel.cu(568): error: expression must have pointer-to-class type

salsa_kernel.cu(570): error: expression must have pointer-to-class type

salsa_kernel.cu(571): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(581): error: expression must have pointer-to-class type

salsa_kernel.cu(582): error: expression must have pointer-to-class type

salsa_kernel.cu(584): error: expression must have pointer-to-class type

salsa_kernel.cu(589): error: expression must have pointer-to-class type

salsa_kernel.cu(590): error: expression must have pointer-to-class type

salsa_kernel.cu(592): error: expression must have pointer-to-class type

salsa_kernel.cu(596): error: expression must have pointer-to-class type

salsa_kernel.cu(605): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(629): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(642): error: identifier "WU_PER_LAUNCH" is undefined

salsa_kernel.cu(645): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(658): error: identifier "WU_PER_LAUNCH" is undefined

salsa_kernel.cu(658): error: identifier "WU_PER_BLOCK" is undefined

salsa_kernel.cu(664): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(675): error: expression must have pointer-to-class type

salsa_kernel.cu(678): error: identifier "checkCudaErrors" is undefined

salsa_kernel.cu(688): error: identifier "WU_PER_LAUNCH" is undefined

salsa_kernel.cu(691): error: identifier "checkCudaErrors" is undefined

**Comment by cbuchner1** [comment]
You should have the Cuda 5.0 Toolkit in /usr/local/cuda (or softlinked under that name). 

Von meinem iPhone gesendet

**Comment by dannyp32** [comment]
I'm getting the same error. I have cuda 5.5 toolkit in /usr/local/cuda
Is 5.0 strictly required or is 5.5 compatible as well?

In my .bashrc I have 
PATH=$PATH:/usr/local/cuda-5.5/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-5.5/lib64:/lib

I've also tried
PATH=$PATH:/usr/local/cuda/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/lib

I still get the same error.

**Comment by hakaba** [comment]
Same error here.
/usr/local/cuda is a symlink ti /usr/local/cuda-5.5

> Ubuntu 12.04

**Comment by zboot** [comment]
Same here running Ubuntu 12.04

**Comment by deltaman** [comment]
Hi,

I got it working by doing:
export LD_LIBRARY_PATH="/usr/local/cuda-5.5/lib64"
export PATH="/usr/local/cuda-5.5/bin:$PATH"

Regards
