### ISSUE TITLE
Path error for nvcc during make

### ISSUE THREAD

**Issue by ghost** [cbuchner1/CudaMiner#16]
The original path defined in the Makefile for `nvcc`, after running `configure.sh` `/usr/local/bin/Cuda/nvcc` is not where the Ubuntu nvidia-cuda-toolkit installs it. I renamed the pathname to `/usr/bin/nvcc` and compilation succeeded.

**Comment by cbuchner1** [comment]
/usr/local/cuda would be the path the configure script is looking for CUDA. That's also where the official nVidia installers will place the CUDA toolkits. There is a command line option in the configure script to override that path, if I remember correctly

To be more precise
/usr/local/cuda-5.0 is where the CUDA 5.0 toolkit will be installed to by the official nVidia toolkit downloads, with a softlink /usr/local/cuda pointing to it.
