### ISSUE TITLE
GTX Titan Linux 64bit "result does not validate on CPU"

### ISSUE THREAD

**Issue by dschmid2** [cbuchner1/CudaMiner#21]
I'm running cudaminer on an opensuse 12.2 with a GTX TITAN with 6GB onboard and 16GB Mainboard Memory. the nvidia driver version is 331.20. 
I get the "result does not validate on CPU" error permanently.
Is there a way or a feature to disable this verification? And what can be the reasons that this test fails?

**Comment by cbuchner1** [comment]
the test fails because the GPU computed a result that's not valid.
Submitting that to the pool wouldn't get you any shares.

2013/11/22 dschmid2 notifications@github.com

**Comment by dschmid2** [comment]
I’m not an expert in cuda, but I guess the kepler implementation is still very young… right?

Von: Christian Buchner [mailto:notifications@github.com] 
Gesendet: Freitag, 22. November 2013 10:33
An: cbuchner1/CudaMiner
Cc: dschmid2
Betreff: Re: [CudaMiner] GTX Titan Linux 64bit "result does not validate on CPU" (#21)

the test fails because the GPU computed a result that's not valid. 
Submitting that to the pool wouldn't get you any shares. 

2013/11/22 dschmid2 < mailto:notifications@github.com notifications@github.com>

**Comment by cbuchner1** [comment]
for me the Titan specific code works fine on a GT 640 (GK 208 chip). 64
kHash/s.

I will be getting a GTX  780 Ti soon for more testing. Expecting 400
kHash/s from it.

I am currently testing on Windows 32+64bit and currently also on Ubuntu
9.04 32bit and Ubuntu 12.04 64 bit.

2013/11/22 dschmid2 notifications@github.com

**Comment by cbuchner1** [comment]
What is the kernel launch configuration that the autotune has determined for you?

**Comment by dschmid2** [comment]
my launch configuration is T28x12
