### ISSUE TITLE
Spinlock_kernel.cu(216) Warning

### ISSUE THREAD

**Issue by Letme** [cbuchner1/CudaMiner#24]
With make install I get warning flood (literally): Cannot tell what pointer points to, assuming global memory space. This is for spinlock_kernel.cu(216) and test_kernel.cu(349) . 
Should I be worried?

When I try to run cudaminer with specific configuration (doesnt matter for autotune as well) it draws horizontal color lines on top of terminal environment (tty1 for example) and gets insanely high hashrates but GPU result fails to validate on CPU. 

I have NVIDIA 325.15 drivers with cuda 5.5  and gfx card is GT 610.

**Comment by Letme** [comment]
And to add - I receive floating point exception (core dumped) if I try to set autotune (something I already so in another issue)

**Comment by Letme** [comment]
OK fixed floating point exception with changing nvcc -arch=compute_10 to nvcc -arch=compute_13 in Makefile at .cu.o: 
Warnings I still cant explain

**Comment by cbuchner1** [comment]
The warning is very common one when targeting Compute 1.x devices (shared
and global memory are in different memory spaces, addressed with different
instructions sets. And occasionally the compiler defaults a pointer to
global memory when it is not sure. I am not sure of any way to turn off the
warning. It does not appear to harm correctness of the code in  my case.

2013/11/29 Crt notifications@github.com
