### ISSUE TITLE
Build problem on FreeBSD 9.2

### ISSUE THREAD

**Issue by kreynolds** [cbuchner1/CudaMiner#26]
In file included from scrypt.cpp:46:
/usr/include/malloc.h:3:2: error: #error "<malloc.h> has been replaced by <stdlib.h>"
scrypt.cpp: In member function 'const uint32x4_t uint32x4_t::operator>>(int) const':
scrypt.cpp:78: error: shift must be an immediate
scrypt.cpp: In member function 'const uint32x4_t uint32x4_t::operator<<(int) const':
scrypt.cpp:77: error: shift must be an immediate
scrypt.cpp:772: confused by earlier errors, bailing out
**\* [cudaminer-scrypt.o] Error code 1

**Comment by kreynolds** [comment]
Note that using GCC48 compiles properly, it is failing with the base GCC 4.2.1, might not be fixable.

**Comment by wmaciel** [comment]
Can confirm the same issue with gcc 4.1.2-52 on CentOS 5.4

**Comment by cbuchner1** [comment]
I guess you have to pick a gcc version that is compatble with your CUDA toolkit. nVidia has documentation about this.
