### ISSUE TITLE
Floating Point Exception caused by configure script creating a makefile with an erroneous arch specification (workaround included)

### ISSUE THREAD

**Issue by marzhall** [cbuchner1/CudaMiner#3]
On Arch Linux with the latest nvidia drivers (319.17-2, https://www.archlinux.org/packages/extra/x86_64/nvidia/) and nvcc 5.0, VO2.1221,
after running the configuration script, a makefile is produced for my NVIDIA GTS 250 that specifies "-arch=compute_10".

Compiling with this option causes an arithmetic error when auto-tune tries to run. Auto-tune output shows all 0s for x1, then crashes with either a floating point exception or an arithmetic error; the output looks like this:

```
[2013-05-17 19:07:24] GPU #0: Performing auto-tuning (Patience...)
[2013-05-17 19:07:24]        x1    x2    x3    x4    x5    x6    x7    x8
[2013-05-17 19:07:24]   1:  0.0                                           kh/s
... (many similar lines)...
[2013-05-17 19:07:24] GPU #0:    0.00 khash/s with configuration  0x0
[2013-05-17 19:07:24] GPU #0: using launch configuration  0x0
Floating point exception (core dumped)
```

 Using gdb, I found that on line 1156 of salsa_kernel.cu,

```
dim3  grid(WU_PER_LAUNCH/WU_PER_BLOCK, 1, 1);
```

WU_PER_BLOCK was evaluating to zero, resulting in a division by zero.

I went through the code, trying to understand how these things were being computed, and ended up seeing that, at line 842, immediately after the line

```
checkCudaErrors(cudaMemcpy(d_idata, h_idata, mem_size, cudaMemcpyHostToDevice)),
```

checking the return value of "cudaPeekAtLastError" in gdb gave me error 13, or "cudaErrorInvalidSymbol." I continued debugging, and saw that after the call of `run_normal_kernel` on line 878 of salsa_kernel.cu, peeking at the last cuda error returned 8. Looking at http://www.cs.cmu.edu/afs/cs/academic/class/15668-s11/www/cuda-doc/html/group__CUDART__TYPES_g3f51e3575c2178246db0a94a430e0038.html, I saw that 8 was `cudaErrorInvalidDeviceFunction`; checking in gdb confirmed this.

I googled this error, and found this udacity link: http://forums.udacity.com/questions/100032430/cuda-error-invalid-device-function-cudagetlasterror, where the commenter reports removing the '-arch' argument from the nvcc call solved his problem.

Checking the makefile, I saw nvcc was being called with the option `-arch=compute_10`; I removed this argument, compiled, and autotune finished successfully. The pool I was hooked up to confirmed the hashes I was sending were correct.

I've created a pull request that removes the arch specification. After this is pulled, I'll likely make this a package on arch linux's user repository.

Thanks for your work!

**Comment by bluszcz** [comment]
Seems related with: https://github.com/cbuchner1/CudaMiner/issues/7

**Comment by marzhall** [comment]
Seems like the same problem. Have you tried compiling without the -arch=compute_10 argument? (Sorry for the delay, was traveling.)

**Comment by bluszcz** [comment]
Well, what helped for me - reinstalling drivers.... It works now.

**Comment by marzhall** [comment]
Awesome! You should update the bug you have open with that info. :)

**Comment by cbuchner1** [comment]
I am pretty sure the compute_10 is needed, as it forces the creation of PTX 1.0 code, which is what I want.
The driver will usually translate the PTX 1.0 code to whatever compute architecture you happen to run.

Christian

**Comment by marzhall** [comment]
In the case of my GTX 250, however, it appears this option is causing nvidia CUDA calls to fail.

I'm away from my computer at the moment, but how would you feel about a pull request that added a "no-compute" option to the config file that allows compilation without "compute_10," and added a CudaError value check after line 878 that printed a warning suggesting using the "no-compute" option to compile and exited if cudaerror returned the "Invalid Device Function" value, suggesting the use had the same issue as myself? After all, once this option is removed, the code functions properly for me.

**Comment by adlerweb** [comment]
Note: Current code does not compile without arch (`ptxas error   : Entry function … uses too much shared data`)
and crashes during autotuning with a floating point exception

**Comment by jra89** [comment]
I tried compiling with a  fresh repository on Linux with the Nvidia 319.60 drivers with a Quadro 3000M card, and I'm also getting this error. I tried removing the -arch=compute_10 from the nvcc call but I still got the same problem. The machine I tested on is at my work so I will have to try some more tomorrow.

**Comment by jefferai** [comment]
On a GT 540M, having this problem with 319.60 drivers on Ubuntu 13.10. I'm launching via optriun. Like @jra89 I also tried removing --arch=compute_10 but also got the same problem.

**Comment by adlerweb** [comment]
Sorta-Workarround: Disable autotune and specify a configuration on the command line...
