### ISSUE TITLE
Build issues with the latest release.

### ISSUE THREAD

**Issue by strasharo** [cbuchner1/CudaMiner#30]
I have the following compile error with the latest pull, I was able to compile the previous releases from git without issues
Ubuntu 12.04.3 LTS x86_64
root@server:~# dpkg --list | grep -i cuda
ii  cuda                                        5.5-22                                  CUDA meta-package
ii  cuda-5-5                                    5.5-22                                  CUDA 5.5 meta-package
ii  cuda-command-line-tools-5-5                 5.5-22                                  CUDA command-line tools
ii  cuda-core-5-5                               5.5-22                                  CUDA core tools
ii  cuda-core-libs-5-5                          5.5-22                                  CUDA native runtime library
ii  cuda-documentation-5-5                      5.5-22                                  CUDA documentation
ii  cuda-extra-libs-5-5                         5.5-22                                  CUDA native libraries
ii  cuda-headers-5-5                            5.5-22                                  CUDA native headers
ii  cuda-license-5-5                            5.5-22                                  CUDA licenses
ii  cuda-misc-5-5                               5.5-22                                  CUDA miscellaneous tools
ii  cuda-repo-ubuntu1204                        5.5-0                                   CUDA repo configuration files.
ii  cuda-samples-5-5                            5.5-22                                  CUDA example applications
ii  cuda-visual-tools-5-5                       5.5-22                                  CUDA visual tools
root@server:~#  

nvcc -g -O2 -arch=compute_10 --maxrregcount=64 --ptxas-options=-v  -o test_kernel.o -c test_kernel.cu
test_kernel.cu(90): error: no suitable constructor exists to convert from "int" to "uint4"

test_kernel.cu(90): error: no suitable conversion function from "uint4" to "unsigned int" exists

test_kernel.cu(91): error: no suitable constructor exists to convert from "int" to "uint4"

test_kernel.cu(91): error: no suitable conversion function from "uint4" to "unsigned int" exists

test_kernel.cu(92): error: no suitable constructor exists to convert from "int" to "uint4"

test_kernel.cu(92): error: no suitable conversion function from "uint4" to "unsigned int" exists

test_kernel.cu(93): error: no suitable constructor exists to convert from "int" to "uint4"

test_kernel.cu(93): error: no suitable conversion function from "uint4" to "unsigned int" exists

test_kernel.cu(155): error: identifier "__ldg" is undefined

test_kernel.cu(191): error: no suitable constructor exists to convert from "int" to "uint4"

test_kernel.cu(191): error: no operator "*" matches these operands
            operand types are: int \* uint4

test_kernel.cu(191): error: identifier "__ldg" is undefined

test_kernel.cu(192): error: no suitable constructor exists to convert from "int" to "uint4"

test_kernel.cu(192): error: no operator "*" matches these operands
            operand types are: int \* uint4

test_kernel.cu(193): error: no suitable constructor exists to convert from "int" to "uint4"

test_kernel.cu(193): error: no operator "*" matches these operands
            operand types are: int \* uint4

test_kernel.cu(194): error: no suitable constructor exists to convert from "int" to "uint4"

test_kernel.cu(194): error: no operator "*" matches these operands
            operand types are: int \* uint4

test_kernel.cu(244): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(245): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(246): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(247): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(250): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(251): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(252): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(253): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(256): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(257): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(258): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(259): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(262): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(263): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(264): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(265): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(268): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(269): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(270): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(271): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(274): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(275): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(276): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(277): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(280): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(281): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(282): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(283): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(286): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(287): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(288): error: identifier "__funnelshift_l" is undefined

test_kernel.cu(289): error: identifier "__funnelshift_l" is undefined

50 errors detected in the compilation of "/tmp/tmpxft_000025c3_00000000-6_test_kernel.cpp1.ii".
make[2]: **\* [test_kernel.o] Error 2
make[2]: Leaving directory `/root/CudaMiner'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/root/CudaMiner'
make: **\* [all] Error 2

**Comment by cbuchner1** [comment]
Run autogen.sh to update Makefile from Makefike.am

Von meinem iPhone gesendet

**Comment by strasharo** [comment]
Cool, that solved it. Thanks! :)
