### ISSUE TITLE
Not building on arch 01/12/13

### ISSUE THREAD

**Issue by lucasmr** [cbuchner1/CudaMiner#31]
Using cudaminer from git and arch updated on 01/12/13, these errors appear when compiling:

http://pastebin.com/aRitBurE

**Comment by cbuchner1** [comment]
Tried running autogen.sh yet? I rarely update Makefile, as I develop in Windows

----- Ursprüngliche Nachricht -----
Von: "lucasmr" notifications@github.com
Gesendet: ‎01.‎12.‎2013 22:28
An: "cbuchner1/CudaMiner" CudaMiner@noreply.github.com
Betreff: [CudaMiner] Not building on arch 01/12/13 (#31)

Using cudaminer from git and arch updated on 01/12/13, these errors appear when compiling:
http://pastebin.com/aRitBurE

**Comment by strasharo** [comment]
That's the same error as mine - https://github.com/cbuchner1/CudaMiner/issues/30.
autogen.sh solved it.

**Comment by lucasmr** [comment]
When running autogen.sh:

Makefile.am:14: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

then configure fails:
./configure: line 6091: syntax error near unexpected token `,'
./configure: line 6091:`LIBCURL_CHECK_CONFIG(, 7.15.2, ,'

curl 7.33.0-3 is installed.

**Comment by flobytho** [comment]
After running autogen.sh I am also having the same problem as lucasmr.

**Comment by lucasmr** [comment]
Checked a fresh copy today, autogen burps this:
configure.ac:116: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

Then configure has the same error as before:
./configure: line 6091: syntax error near unexpected token `,'
./configure: line 6091:`LIBCURL_CHECK_CONFIG(, 7.15.2, ,'

**Comment by spanishconnector** [comment]
I'm using Ubuntu 12.04, The error below that lucasmr is getting for ./autogen.sh :
configure.ac:116: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

I was able to fix it with sudo apt-get install nvidia-cuda-toolkit 

Now, I am getting the following message in the end when I run ./configure :

./configure: line 6032: syntax error near unexpected token `,'
./configure: line 6032:`LIBCURL_CHECK_CONFIG(, 7.15.2, ,'

I am new to mining and to Cuda. Thank you in advance for any help.

**Comment by spanishconnector** [comment]
I fixed the following error message for ./configure:

./configure: line 6032: syntax error near unexpected token ,'
./configure: line 6032:LIBCURL_CHECK_CONFIG(, 7.15.2, ,'

I used the following commands on Ubuntu 12.04:

sudo aptitude install libcurl-dev 
sudo apt-get install libcurl4-gnutls-dev

I hope it helps.

**Comment by leshow** [comment]
running into the same problems as lucasmr with arch

**Comment by leshow** [comment]
i should note that i get this error when running autogen.sh on arch linux

leshow@leshowbox:~/CudaMiner(master⚡) » ./autogen.sh 
configure.ac:116: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Comment by mynameisrufus** [comment]
`wget https://raw.github.com/rallat/quarkcoin-cpuminer/4e6c263c837bd04261df1ba7383ea828409ff498/acinclude.m4`

The run /autogen.sh

**Comment by leshow** [comment]
what file is that?

**Comment by lucasmr** [comment]
On Fedora 20 the same error happens.

$ make clean
$ ./autogen.sh
$ ./configure

./configure: line 6116: syntax error near unexpected token `,'
./configure: line 6116:`LIBCURL_CHECK_CONFIG(, 7.15.2, ,'

libcurl and libcurl-devel are installed:

Package libcurl-7.32.0-3.fc20.x86_64 already installed and latest version.
Package libcurl-devel-7.32.0-3.fc20.x86_64 already installed and latest version

**Comment by oldtopman** [comment]
Doesn't build on Slackware 14.0_64 either, same as lucasmr.
mynameisrufus' file does get it to build successfully.

**Comment by DougPuchalski** [comment]
`sudo apt-get install libcurl4-openssl-dev` fixed this for me on Ubuntu 12.10

**Comment by mmalka** [comment]
You need to run "apt-get install libcurl4-openssl-dev" (or any newer version for the future),
then restart the autogen.sh or it will keep the error.
