### ISSUE TITLE
CudaMiner issue while make

### ISSUE THREAD

**Issue by tachyon-ops** [cbuchner1/CudaMiner#35]
So.. I've issued 'PATH=/usr/local/cuda-5.5/bin:$PATH make'

Everything seams cool, but then I get this output:

http://bitbin.it/XAMI3szy

For a quick resume: 

test_kernel.cu(289): error: identifier "__funnelshift_l" is undefined

50 errors detected in the compilation of "/tmp/tmpxft_000018c8_00000000-6_test_kernel.cpp1.ii".
make[2]: **\* [test_kernel.o] Error 2
make[2]: Leaving directory `/home/<USER>/mining/CudaMiner'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/<USER>/mining/CudaMiner'
make: **\* [all] Error 2

Anyone has an idea? Thanks

*edit: I'm on Fedora 19:

 ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 520"
  CUDA Driver Version / Runtime Version          6.0 / 5.5
  CUDA Capability Major/Minor version number:    2.1
  Total amount of global memory:                 1023 MBytes (1072889856 bytes)
  ( 1) Multiprocessors, ( 48) CUDA Cores/MP:     48 CUDA Cores
  GPU Clock rate:                                1620 MHz (1.62 GHz)
  Memory Clock rate:                             600 Mhz
  Memory Bus Width:                              64-bit
  L2 Cache Size:                                 65536 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65535), 3D=(2048, 2048, 2048)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (65535, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Bus ID / PCI location ID:           2 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 6.0, CUDA Runtime Version = 5.5, NumDevs = 1, Device0 = GeForce GT 520
Result = PASS

**Comment by cbuchner1** [comment]
Git pull or ./autogen.sh will help

Am Montag, 2. Dezember 2013 schrieb nmpribeiro :

**Comment by tachyon-ops** [comment]
CudaMiner]# sh autogen.sh
Makefile.am:14: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

great, I have done that, then ./compile then make and it created cudaminer. Now... hehe:

./cudaminer
./cudaminer: error while loading shared libraries: libjansson.so.4: cannot open shared object file: No such file or directory

gonna check if there is some solution to that

_edit: just 'yum install libjansson_'

fixed...
