### ISSUE TITLE
Error on building on CentOS

### ISSUE THREAD

**Issue by fortrano** [cbuchner1/CudaMiner#39]
On CentOS I am getting errors on make:

Makefile:381: .deps/cudaminer-cpu-miner.Po: No such file or directory
Makefile:382: .deps/cudaminer-scrypt.Po: No such file or directory
Makefile:383: .deps/cudaminer-sha2.Po: No such file or directory
Makefile:384: .deps/cudaminer-util.Po: No such file or directory
make: **\* No rule to make target `.deps/cudaminer-util.Po'.  Stop.

These relate to following lines in the makefile:

include ./$(DEPDIR)/cudaminer-cpu-miner.Po
include ./$(DEPDIR)/cudaminer-scrypt.Po
include ./$(DEPDIR)/cudaminer-sha2.Po
include ./$(DEPDIR)/cudaminer-util.Po

When I comment those out make runs a bit further, resulting in a similar error message:

Makefile:254: .deps/dump.Po: No such file or directory
Makefile:255: .deps/hashtable.Po: No such file or directory
Makefile:256: .deps/load.Po: No such file or directory
Makefile:257: .deps/strbuffer.Po: No such file or directory
Makefile:258: .deps/utf.Po: No such file or directory
Makefile:259: .deps/value.Po: No such file or directory
make[3]: **\* No rule to make target `.deps/value.Po'.  Stop.

relating to 

include ./$(DEPDIR)/dump.Po
include ./$(DEPDIR)/hashtable.Po
include ./$(DEPDIR)/load.Po
include ./$(DEPDIR)/strbuffer.Po
include ./$(DEPDIR)/utf.Po
include ./$(DEPDIR)/value.Po

Commenting those out leads to a chain of errors:

source='dump.c' object='dump.o' libtool=no \
        DEPDIR=.deps depmode=none /bin/sh ../../depcomp \
        gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..     -O3 -c dump.c
: command not found 3:
: command not found 5:
: command not found 8:
: command not found 13:
: command not found 18:
: command not found 21:
: command not found 26:
: command not found 28:
'./../depcomp: line 29: syntax error near unexpected token `in
'./../depcomp: line 29:`case $1 in
make[3]: **\* [dump.o] Error 2

And finally exiting.

What can I do to resolve this?

**Comment by jbroome** [comment]
This is still an issue, what was the resolution?
