### ISSUE TITLE
Unable to compile spinlock_kernel.o

### ISSUE THREAD

**Issue by phobeus81** [cbuchner1/CudaMiner#42]
## When trying to compile the most recent version from the repository, nvcc is raising an exception and fails to compile spinlock_kernel.o.

make  all-recursive
make[1]: Entering directory `/home/phobeus/src/cudaminer'
Making all in compat
make[2]: Entering directory`/home/phobeus/src/cudaminer/compat'
make[3]: Entering directory `/home/phobeus/src/cudaminer/compat'
make[3]: Nothing to be done for`all-am'.
make[3]: Leaving directory `/home/phobeus/src/cudaminer/compat'
make[2]: Leaving directory`/home/phobeus/src/cudaminer/compat'
make[2]: Entering directory `/home/phobeus/src/cudaminer'
nvcc -g -O2 -Xptxas "-abi=no -v" -arch=compute_30 --maxrregcount=63  -o spinlock_kernel.o -c spinlock_kernel.cu
UNREACHABLE executed!
Stack dump:
0.      Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_Z28spinlock_scrypt_core_kernelBILi3EEvPjPi'
nvcc error   : 'cicc' died due to signal 6 
nvcc error   : 'cicc' core dumped
make[2]: *** [spinlock_kernel.o] Error 134
make[2]: Leaving directory`/home/phobeus/src/cudaminer'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/home/phobeus/src/cudaminer'
## make: **\* [all] Error 2

When using a older version with commit "88c6da6d5c2b798d1de7031e8dbcc2678f635e4b" it seems to be compiling fine.

**Comment by cbuchner1** [comment]
Use cuda 5.0 toolkit - nvidia still offer it for download

----- Ursprüngliche Nachricht -----
Von: "phobeus81" notifications@github.com
Gesendet: ‎05.‎12.‎2013 20:40
An: "cbuchner1/CudaMiner" CudaMiner@noreply.github.com
Betreff: [CudaMiner] Unable to compile spinlock_kernel.o (#42)

When trying to compile the most recent version from the repository, nvcc is raising an exception and fails to compile spinlock_kernel.o.
make all-recursive
make[1]: Entering directory /home/phobeus/src/cudaminer'
Making all in compat
make[2]: Entering directory/home/phobeus/src/cudaminer/compat'
make[3]: Entering directory /home/phobeus/src/cudaminer/compat'
make[3]: Nothing to be done forall-am'.
make[3]: Leaving directory /home/phobeus/src/cudaminer/compat'
make[2]: Leaving directory/home/phobeus/src/cudaminer/compat'
make[2]: Entering directory /home/phobeus/src/cudaminer'
nvcc -g -O2 -Xptxas "-abi=no -v" -arch=compute_30 --maxrregcount=63 -o spinlock_kernel.o -c spinlock_kernel.cu
UNREACHABLE executed!
Stack dump:
0. Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_Z28spinlock_scrypt_core_kernelBILi3EEvPjPi'
nvcc error : 'cicc' died due to signal 6 
nvcc error : 'cicc' core dumped
make[2]: **\* [spinlock_kernel.o] Error 134
make[2]: Leaving directory/home/phobeus/src/cudaminer'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/home/phobeus/src/cudaminer'
make: **\* [all] Error 2
When using a older version with commit "88c6da6d5c2b798d1de7031e8dbcc2678f635e4b" it seems to be compiling fine.

**Comment by phobeus81** [comment]
Okay, if it is not working with Cuda 5.5, I am having an issue as the Cuda 5.0 does not support any GCC higher than 4.7 that is delivered with most recent linux distributions. Just curious about it as it seems to be working fine with other versions from november.

**Comment by cbuchner1** [comment]
I now use some compiler flags that cause CUDA 5.5 to barf, but give higher performance on 5.0

**Comment by phobeus81** [comment]
Okay, confirming. When going back to commit 595a0a901d998fe574f3b299af04d42446c52222 on the Makefiles in the root and the compat, I am able to compile a version running fine with 5.5 as well. Maybe adding some switch for handling this instead? Like said, most recent distributions might have issues compiling against Cuda 5.0. Having an flag in there might be an option. Else configure shall check for version and giving an appropriate error message as the spin compile failure might not be indicating an incompatibility with cuda version.

**Comment by strasharo** [comment]
Same issue on Ubuntu 12.04.3 LTS x86_64 with cuda 5.5:
gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -msse2  -fopenmp -pthread -fno-strict-aliasing -I./compat/jansson   -g -O2 -MT cudaminer-cpu-miner.o -MD -MP -MF .deps/cudaminer-cpu-miner.Tpo -c -o cudaminer-cpu-miner.o `test -f 'cpu-miner.c' || echo './'`cpu-miner.c
mv -f .deps/cudaminer-cpu-miner.Tpo .deps/cudaminer-cpu-miner.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -msse2  -fopenmp -pthread -fno-strict-aliasing -I./compat/jansson   -g -O2 -MT cudaminer-util.o -MD -MP -MF .deps/cudaminer-util.Tpo -c -o cudaminer-util.o `test -f 'util.c' || echo './'`util.c
mv -f .deps/cudaminer-util.Tpo .deps/cudaminer-util.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -msse2  -fopenmp -pthread -fno-strict-aliasing -I./compat/jansson   -g -O2 -MT cudaminer-sha2.o -MD -MP -MF .deps/cudaminer-sha2.Tpo -c -o cudaminer-sha2.o `test -f 'sha2.c' || echo './'`sha2.c
mv -f .deps/cudaminer-sha2.Tpo .deps/cudaminer-sha2.Po
g++ -DHAVE_CONFIG_H -I.  -msse2  -fopenmp -pthread -fno-strict-aliasing -I./compat/jansson   -g -O2 -MT cudaminer-scrypt.o -MD -MP -MF .deps/cudaminer-scrypt.Tpo -c -o cudaminer-scrypt.o `test -f 'scrypt.cpp' || echo './'`scrypt.cpp
mv -f .deps/cudaminer-scrypt.Tpo .deps/cudaminer-scrypt.Po
nvcc -g -O2 -arch=compute_10 --maxrregcount=124 --ptxas-options=-v -I./compat/jansson -o salsa_kernel.o -c salsa_kernel.cu
nvcc -g -O2 -Xptxas "-abi=no -v" -arch=compute_30 --maxrregcount=63 -I./compat/jansson -o spinlock_kernel.o -c spinlock_kernel.cu
UNREACHABLE executed!
Stack dump:
0.  Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_Z28spinlock_scrypt_core_kernelBILi3EEvPj'
Aborted (core dumped)
make[2]: **\* [spinlock_kernel.o] Error 134
make[2]: Leaving directory `/root/CudaMiner'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/root/CudaMiner'
make: **\* [all] Error 2

Will try to revert to Cuda 5.0 and report back.

**Comment by ghost** [comment]
I got this error.
nvcc -g -O2 -Xptxas "-abi=no -v" -arch=compute_30 --maxrregcount=63  -o spinlock_kernel.o -c spinlock_kernel.cu
UNREACHABLE executed!
Stack dump:
0.  Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_Z28spinlock_scrypt_core_kernelBILi3EEvPj'
Aborted

**Comment by cbuchner1** [comment]
using CUDA 5.0 instead of CUDA 5.5 would be the solution.

2013/12/13 Armando notifications@github.com

**Comment by snakkewang** [comment]
not CUDA 5.0 any more

**Comment by cbuchner1** [comment]
https://developer.nvidia.com/cuda-toolkit-50-archive

2013/12/14 snakkewang notifications@github.com

**Comment by OnkelTem** [comment]
Also getting that error.

CUDA 5.0 is outdated (two years, since 2012) and is not an option for some cars like mine - GeForce 640 which is not detected as CUDA supporting.
CUDA 5.5 works fine and detects my card.

Please make the miner working with CUDA 5.5.

best,
Artem

**Comment by cbuchner1** [comment]
I am mining on three GT 640, two GK108 and one GK208 chips running
cudaminer binaries built with CUDA 5.0 (using fairly recent nVidia drivers)

also have a look at this
https://github.com/cbuchner1/CudaMiner/blob/master/README

2013/12/14 Artiom Neganov notifications@github.com

**Comment by ghost** [comment]
its not a recommend to do cuda 5.0, My OS break becouse need to downgrade to and old versio of gcc

**Comment by jaromil** [comment]
Hi there, those wanting to use cuda 5.5 can simply change the Makefile. Where it says:

<pre>
spinlock_kernel.o: spinlock_kernel.cu
        $(NVCC) -Xptxas "-abi=no -v" -arch=compute_11 --maxrregcount=124 $(JANSSON_INCLUDES) -o $@ -c $<
</pre>

revert to old flags:

<pre>
        $(NVCC) -Xptxas "-abi=no -v" -arch=compute_35 --maxrregcount=64 $(JANSSON_INCLUDES) -o $@ -c $<
</pre>

et voila'.

**Comment by jaromil** [comment]
Apologies for the previous comment, it is confusing. I meant that old compile flags "-arch=compute_11 --maxrregcount=124" will compile the spinlock_kernel using cuda 5.5 nvcc. Anyway this will produce a cudaminer that is slightly slower than the older for my testing hardware (GT 610).

**Comment by carowjp** [comment]
Hi.  I'm trying to compile for Cuda 5.5 also and am confused.. I tried the Makefile change in your earlier post and now get:

spinlock_kernel.cu(340): error: identifier "atomicCAS" is undefined

spinlock_kernel.cu(345): error: identifier "atomicExch" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00002640_00000000-6_spinlock_kernel.cpp1.ii".

**Comment by ghost** [comment]
well it compile and i got this meesage runnind.

GPU #0: maximum warps: 217
 GPU #0:    3.97 khash/s with configuration L4x3
  using launch configuration L4x3
GeForce 9400 GT, 4224 hashes, 1.04 khash/s

its slow.

**Comment by gstacks** [comment]
Hey Guys,
I dont know how to compile, and I dont know what a nvcc is.  I would love to learn more, any help or direction would be greatly appreciated.  Happy Holidays!!!
TY!

**Comment by cbuchner1** [comment]
There is a chance that I will migrate the project to CUDA 5.5, because I am seeing a 20-30% gain with CUDA 5.5 only while it is limited to 5-10% using CUDA 5.0. This is with Dave Andersen's improved Keplerminer code, integrated into cudaminer.

**Comment by ghost** [comment]
First what plataform are you using (windows, mac or linux) ?

nvcc its the compiler for CUDA.

**Comment by gstacks** [comment]
I am using Win 7 64 bit.   Oh nvcc is the compiler.  Awesome!  I have to now learn how to compile.  :)

**Comment by gbougard** [comment]
Hi,
got here the same issue until last 57dd2bf08fd592eb2025355f0abe598438ee1b9b commit.
Now, it builds almost fine but with warnings under linux Fedora 19, x86_64 and with CUDA 5.5.
I'm having 15.2kH/s now with my GeForce 9600 GT, x7.5 against 2kH/s with cgminer.
Thank you for that good work.

**Comment by jaromil** [comment]
Yep! now compiles on CUDA 5.5 (just tested on stock Ubuntu 12.04 x86_64)

auto-tuning choose kernel F44x5 with a 14.43 khash/s which makes it now as fast as the old spinlock version

cheers Christian!

**Comment by cbuchner1** [comment]
this is an outdated ticket. closing.
