### ISSUE TITLE
Results do not validate on CPU (GTX 460)

### ISSUE THREAD

**Issue by javdrher** [cbuchner1/CudaMiner#45]
Hi,

I'm using the 1th of december release of cudaminer, with CUDA 5.5 on an opensuse system with 1 GTX 460. Autoconfig selects F56x2 or F14x8 randomly. When I run cudaminer, I switch to a real terminal and drop the GUI to save GPU memory for mining. I set the device to interactive.

However, three days ago I noticed weird green and yellow pixels on my screen when I start cudaminer. I assumed this to be caused by the screen buffer overlapping with the memory used for computation. This was not a problem, but I noticed that after a while my results do not longer validate. On my screen this occurs when console text overwrites these green areas. I redirected all output of the command into a file to avoid these issues but it only works for a while because sometimes the screen buffers do get touched and cause failing to occur. Having the computation data in the screen buffers doesn't seem to be a good idea anyway.

How should I resolve these issues? I'm not 100% convinced this is a bug, rather a combination of circumstances. I could try to use CUDA 5.0 perhaps? or run in it from a graphical session so perhaps cudaminer avoids these memory regions? (although it may cost some khash, right now faillure means some hours of mining downtime which is worse).

**Comment by cbuchner1** [comment]
It could also be a faulty or incompatible driver version. Try downgrading
your CUDA toolkit to 5.0 first.

I don't have any experience running CUDA without a running X Server. Does
this not occur while the graphics remains enabled?

Christian

2013/12/9 xeonvl notifications@github.com

**Comment by javdrher** [comment]
Small update: I had very little time last night so I did not try CUDA 5.0. I started the miner with X server turned on and it seems to work stable now (just slightly slower). I guess this is more a CUDA issue

**Comment by hammackj** [comment]
I am getting this error also all of a sudden. Not sure what is different, My configs have not changed.

**Comment by kingcrunch** [comment]
Here too on a small GTS450. It worked fine before I updated today (before I used at most 2 weeks old `master`).

**Comment by magnux** [comment]
I have a GTX570, and it works fine with the version previous to the bump to CUDA 5.5 and driver nvidia-304-updates. When I try to update to the latest version and driver 319 (also tried 310) which supports CUDA 5.5, all of the sudden I get this error and about 95% of the shares are lost. I don't know if it is the new version breaking something, or the new driver, or the combination. I don't change anything else, same config, same user, same everything, just updating, breaks it :(. btw, nice work cbuchner1. I almost forgot: I use Ubuntu 13.10, although I don't think that matters for this particular bug.

**Comment by magnux** [comment]
Duh!. I realized today reading the commits that the new implementation of the kernel is only working for Kepler based cards which are 600 series and newer. Code for Fermi based cards (400 and 500 series) is currently being worked on, so we need to wait for the adaptation of the code. That's the cause of this, most probably. Just use the Latest Cuda 5.0 release and you should be fine, for a few days.

**Comment by magnux** [comment]
Ok, now I think the problem is because we are using Cuda 5.0 instead of 5.5, and although cudaminer wont complain at start if you have driver 319, it actually doesn't have Cuda 5.5 so it maybe causing all these troubles. So we need to manually install Cuda 5.5 and try again. I will give it a shot myself, after work.

**Comment by magnux** [comment]
Good news is that after manual install of 5.5, it does work. Here are some fine tips for the upgrade: http://askubuntu.com/questions/380609/anyone-has-successfully-installed-cuda-5-5-on-ubuntu-13-10-64-bit
Bad news is that the newer version doesn't seem to get me any more Kh/s :(. But at least I can update from now on.

**Comment by cbuchner1** [comment]
this is now a duplicate ticket. And the latest github version should have no issues with either CUDA 5.0 or 5.5
