### ISSUE TITLE
Hash rate skyrockets but no work gets done

### ISSUE THREAD

**Issue by gosnmic** [cbuchner1/CudaMiner#55]
I've had this happen twice now mining two different coin types (first Doge, now FTC). It'll be going along fine for quite some time (e.g., day, well over 6500 accepted at >99%) and then the hash rate jumps wildly but nothing is ever submitted. I was going to do a little copy and paste but it's off screen now ... essentially I get ~62kH/sec off my GPU with normal action (that's after upgrading to the 12/20 version running on a Geforce GTX 650). Then something apparently happens internally and the reported hash rate skyrockets to something like 250kH/sec and it appears to continue communicating, knowing when new blocks are found. However, nothing seems to be returned as accepted or rejected once at the super-hash-rate - it just completely drops off.

**Comment by AmanitaVerna** [comment]
This or something similar happens to me consistently with my GTX 460 - it skyrockets up to 897ish (give or take a bit) khash/sec, with both the 12/10 and 12/18 versions posted on https://bitcointalk.org/index.php?topic=167229.0 . I determined that what was actually happening was that the video card drivers were crashing while cudaminer was running, and that was precisely when cudaminer changed from a normal speed and saying yay, to ludicrous speeds but no actual work. So, I updated my video card drivers to the latest stable version in hopes that would fix it, but that only made cudaminer crash if the auto-tuner wasn't bypassed, and made the 12/18 version runnable (my previous drivers were too old and only worked with the 12/10 version - but autotune worked). 

It is consistently crashing after 1-3 hours of operation, even if the computer is left alone and not used while it is running.

The video card driver crash leaves failures in the windows reliability monitor's log (labelled 'video hardware error'). I actually observed it happen once, and when it did both my screens went black for several seconds, and the video card fan noise dropped in volume considerably (back to an idling level), and there was no response to my moving the mouse, pressing keys, etc. Several seconds later, windows reappeared, and a system tray popup appeared announcing the driver crash. I had EVGA Precision X running as well, so I could see that the GPU usage had dropped from 94% or so down to almost nothing, and the temperature and fan speed had dropped as well. The temperature gets up to 74C (possibly higher with hardware fan control? Would have to retest) while running the 12/18 version of cudaminer. GPU memory usage with the 12/18 version is only at 830 MB (out of 1024).

I just altered the software fan curve in EVGA Precision X to run at 100% fan speed (holding the temperature down to 69-70C while cudaminer runs). Cudaminer is getting ~103 khash/sec using cudaminer.exe --no-autotune -l 14x8 -o stratum+tcp://stratum.dogehouse.org:3333 -O User.Worker:Password

Will report back if the drivers still crash with the GPU fan going at full speed (It is quite a bit louder for only fiveish degrees cooler).

Edit: Drivers still crashed, after around 2 hours.

**Comment by AmanitaVerna** [comment]
Haven't crashed since changing the .bat to run it with --no-autotune -l F7x16 -C 2 (3 hours ago).

I was running it with --no-autotune -l 14x8 (because I didn't know what the -l parameter meant yet and it SEEMED to work)
Aside: Prior to updating my graphics drivers, I was running it with the autotune, and whatever it was selecting was also eventually causing a graphics driver crash, so...

So running it with improper -l settings (or getting bad settings from autotune) might have been the cause.

Edit: Nevermind, video card drivers just crashed again. It lasted 3 hours 20 minutes this time. vOv

**Comment by gosnmic** [comment]
Well thanks for the feedback. Incidentally, I started mine a couple days ago and it's still going fine (I though for sure I'd come back and it'd be 'off' again). I'll have to try to catch it when it happens to take note if I'm doing much of anything graphics-related at the time. I'm operating under linux so I'm not sure what additional impact(s) that has concerning drivers & versions. >100kh/sec?! I guess I didn't realize just how underpowered this card really was (though I didn't buy it with the intention to Scrypt mine)! Good luck ironing out your driver issues! Since it sounds like the culprit isn't anything in the CudaMiner code, I'm closing this out.
