### ISSUE TITLE
*** stack smashing detected ***: cudaminer terminated

### ISSUE THREAD

**Issue by ghost** [cbuchner1/CudaMiner#6]
I got a stack smashing detected error:

**\* stack smashing detected ***: cudaminer terminated

I am using ubuntu 12.10, Asus GTX 660TI, gcc4.6, cuda5

**Comment by cbuchner1** [comment]
got any code line or function name where this happened?

2013/7/1 ivan ceras notifications@github.com

**Comment by ghost** [comment]
I can't tell which line in the code. I checked out the code last june 29 ( 3 days ago) from the master branch. It just shows the 
"**\* stack smashing detected ***:  Aborting core dump.." message.

I checkout the code just after submitting this issue. Recompiled then run.
Now working fine at 140Khash/s on litecoins.
