### ISSUE TITLE
Undefined reference to 'scanhash_scrypt_jane'

### ISSUE THREAD

**Issue by poleethman** [cbuchner1/CudaMiner#60]
Running 'make' on Linux Mint 15 64 bit throws this error: 

cudaminer-cpu-miner.o: In function `miner_thread':
cpu-miner.c:(.text+0x2f5d): undefined reference to`scanhash_scrypt_jane'
collect2: error: ld returned 1 exit status

The binary file cudaminer-cpu-miner.o that's created by the Makefile seems to be looking for the 'scanhash_scrypt_jane' that's not defined, but I can't find where it's doing that, or not doing that.

**Comment by kurzz** [comment]
I am getting the exact same error. Stopping at the same point. This must be a new bug with the latest update, it compiled fine a few weeks ago.

Ubuntu 13.10 64-bit

cudaminer-cpu-miner.o: In function `miner_thread':
cpu-miner.c:820: undefined reference to`scanhash_scrypt_jane'

**Comment by cbuchner1** [comment]
dudes, run ./autogen.sh and configure first

2014/1/4 kurzz notifications@github.com

**Comment by poleethman** [comment]
That worked.  I usually skip everything that says (Optional) just to see if I can get it in working order first.
