### ISSUE TITLE
6.5% performance regression on kepler

### ISSUE THREAD

**Issue by silinxey** [cbuchner1/CudaMiner#61]
Noticing performance regression on kepler with commits 87ae8ef and cc3bcaf.

> ./cudaminer -l K10x16 -C 1 -i 0 --benchmark
> 1 miner threads started, using 'scrypt' algorithm.
> GeForce GTX 660 with compute capability 3.0
> interactive: 0, tex-cache: 1D, single-alloc: 1
> using launch configuration K10x16

a1ecdf9 191.18 khash/s
87ae8ef 184.99 khash/s
...
2c2edc8 184.96 khash/s
cc3bcaf 178.72 khash/s

**Comment by cbuchner1** [comment]
This is one of the reasons I haven't called the ongoing work a new release
yet.

I am currently working on scrypt-jane without testing/verifying scrypt
performance.

A possible cause for the regression might be the use of a non-constant
expression for the SCRATCH #define in the Kepler kernel, which has to do a
dynamic evaluation at run time.

Christian

**Comment by gbougard** [comment]
@silinxey :
Hi, when to copy/paste "using launch configuration K10x1", did you shrink the output from the "6" or not ? If not, this means the "--benchmark" forced cudaminer to select another configuration setting than the one you specified on commandline, and "K10x1" is surely less efficient than "K10x16" making rate less reliable other time.

Myself I found that benchmarking is not reliable. You should try "--debug" to see all settings cudaminer is benchmarking. Compare your output between few runs, you may see some differences. Try also with and without "-i", "-C" and "-m" option. This is just the way I found the best settings for my card. After that, I don't use "--benchmark", this is no more useful when found the best setting and using "-l" option.

@cbuchner1 :
Personnaly I really think the benchmarking algorythm in cudaminer should be a little tuned to be more reliable.

**Comment by cbuchner1** [comment]
The new kernels submitted by nVidia (Y and Z) are much faster anyway. I might still check why some commits made the K kernel slower - as the K kernel is currently best for scrypt-jane mining. And any unnecessary performance regression might also affect the jane speed.
