### ISSUE TITLE
CPU result validation fails whatever parameters I use

### ISSUE THREAD

**Issue by skubo** [cbuchner1/CudaMiner#65]
Using current master branch from 16.1.2014 and GeForce GT 630

I keep getting CPU hash validation failures no matter what parameters I feed to CudaMiner. 

Debug output shows this: 
DEBUG: hash <= target
Hash:   000007747bc6fd19cdc6b5915954734463df965d35b902741c5fdf9777023a31
Target: 00000ffff0000000000000000000000000000000000000000000000000000000

Platform is Ubuntu 13.04 with Nvidia driver 319 and cuda 5.5

Am I doing something wrong?

**Comment by cbuchner1** [comment]
how current is the branch? ;) I made some commits today that fixed an
autotune problem (out of memory error).

Is the GT630 a Fermi part or one based on GK208 Kepler?

Are you hashing scrypt or scrypt-jane coins?

2014/1/16 skubo notifications@github.com

**Comment by skubo** [comment]
Am using the one after your commits today. (had the validation fails before and after these)

Autodetect always falls to F... configurations so I believe it's Fermi. 

I'm mining scrypt coins

**Comment by skubo** [comment]
Just found that if using legacy mode, it actually works (with lower hashrates of course...) It's definetly not Kepler, found that out now.

**Comment by skubo** [comment]
Can be closed. On lastest master Fermi kernels verify on CPU now on Ubuntu 13.04
