### ISSUE TITLE
GeForce GTX 650 result does not validate on CPU 1228 khas/s

### ISSUE THREAD

**Issue by ilyacherevkov** [cbuchner1/CudaMiner#67]
Just installed CudaMiner on OSX (Mavericks withGeForce GTX 650)

Used this parameters

 ./cudaminer -d 0 -i 0 -l K12x16 -C 1 -H 1 -o stratum+tcp://pool.d2.cc:3333 -O miner:pass

The output is 

GPU #0: GeForce GTX 650, 1228 khas/s
GPU #0: GeForce GTX 650 result does not validate on CPU

Is there something I can do with it?

**Comment by ilyacherevkov** [comment]
Btw,

If I run 

./cudaminer -H 1 -m 1 -i 0 -l K12x16 -o stratum+tcp://pool.d2.cc:3333 -O worker:pass

hasrate is around 82 khas/s and there is no error. I think the key is with -C 1 parameter. Of course, as you can imagine, I would like to stick with 1000+ khas/s :) Is this completely not possible to find a workaround?

**Comment by cbuchner1** [comment]
-C 1 made the kernel crash. The latest versions have a check and auto-upgrade to -C 2 if the texture dimensions are exceeded.
