### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by bluszcz** [cbuchner1/CudaMiner#7]
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 02) (prog-if 00 [VGA controller])

./cudaminer -u xxx-p xxxx  -o stratum+tcp://mining.eu.hypernova.pw:3333 -d 0 -i 0 -l auto
           **\* CudaMiner for nVidia GPUs by Christian Buchner ***
                     This is version 2013-07-13 (alpha)
        based on pooler-cpuminer 2.3.2 (c) 2010 Jeff Garzik, 2012 pooler
               Cuda additions Copyright 2013 Christian Buchner
           My donation address: LKS1WDKGED647msBQfLBHV3Ls8sveGncnm

[2013-07-17 16:59:47] Starting Stratum on stratum+tcp://mining.eu.hypernova.pw:3333
[2013-07-17 16:59:47] 1 miner threads started, using 'scrypt' algorithm.
[2013-07-17 16:59:47] Stratum detected new block
[2013-07-17 16:59:48] GPU #0: starting up...

[2013-07-17 16:59:48] GPU #0:  with compute capability 402655552.32735
[2013-07-17 16:59:48] GPU #0: interactive: 0, tex-cache: 0 , single-alloc: 0
[2013-07-17 16:59:48] GPU #0: Performing auto-tuning (Patience...)
[2013-07-17 16:59:48] GPU #0:    0.00 khash/s with configuration  0x0
[2013-07-17 16:59:48] GPU #0: using launch configuration  0x0
Floating point exception (core dumped)

**Comment by bluszcz** [comment]
Ubuntu 13.04.

With these packages installed:

ii  nvidia-304                                          304.88-0ubuntu1                             amd64        NVIDIA binary Xorg driver, kernel module and VDPAU library
ii  nvidia-common                                       1:0.2.76                                    amd64        transitional package for ubuntu-drivers-common
ii  nvidia-cuda-dev                                     5.0.35-4ubuntu1                             amd64        NVIDIA CUDA development files
ii  nvidia-cuda-doc                                     5.0.35-4ubuntu1                             all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                                     5.0.35-4ubuntu1                             amd64        NVIDIA CUDA GDB
ii  nvidia-cuda-toolkit                                 5.0.35-4ubuntu1                             amd64        NVIDIA CUDA toolkit
ii  nvidia-current                                      304.88-0ubuntu1                             amd64        Transitional package for nvidia-current
ii  nvidia-opencl-dev                                   5.0.35-4ubuntu1                             amd64        NVIDIA OpenCL development files
ii  nvidia-profiler                                     5.0.35-4ubuntu1                             amd64        NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings-304                                 304.88-0ubuntu1                             amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-visual-profiler                              5.0.35-4ubuntu1                             amd64        NVIDIA Visual Profiler

**Comment by bluszcz** [comment]
And dmesg:

[  748.114365] traps: cudaminer[6146] trap divide error ip:41a86f sp:7f9781a49520 error:0 in cudaminer[400000+27f000]
[  999.097689] traps: cudaminer[4204] trap divide error ip:41a86f sp:7fe82e812520 error:0 in cudaminer[400000+27f000]
[ 1005.226691] traps: cudaminer[4228] trap divide error ip:41a86f sp:7f915b7dd520 error:0 in cudaminer[400000+27f000]
[ 1048.776613] traps: cudaminer[4280] trap divide error ip:41a86f sp:7fdf2451e520 error:0 in cudaminer[400000+27f000]

**Comment by michalsarna** [comment]
Yep.
Try to understand it's for nVidia GPU's ONLY.
No intel support. 

All best

**Comment by bluszcz** [comment]
I understand, there is no really point that you have to scream at the end of the sentence. Please keep calm and focus on the goals ;)

This card its NVIDIA Optimus http://en.wikipedia.org/wiki/Nvidia_Optimus  / Switching from INTEL / NVIDIA Mode when the apps asks for GL mode. I didn't mentioned also, that I  have second same laptop with same GPU  and I mining there with latest cudaminer using scrypt around 25Kh/s.

Cheers.

**Comment by cbuchner1** [comment]
Optimus requires software like bumblebee and the "optirun" tool to launch cudaminer. See a related forum posting I made on the bitcointalk thread.

**Comment by michalsarna** [comment]
There is no mention of nVidia GPU in what You have posted. So try to be more specific with a hardware configuration next time.

All best.

**Comment by bluszcz** [comment]
Hi Christian. I think I have read - but going to check anyway to make sure. On my second setup - I didn't use explicity optirun neither bumblebee - latets versions of nvidia driver 319 provides support for it (I have them installed not trough dpkg).

Packages which I have installed they are from 304 to provide depends for headers but there is also binary 319, which supposed to clean after not necessary parts 304.... Maybe its related with driver itself, but I have seen also other similar issues with segfaults.

**Comment by bluszcz** [comment]
@michalsarna Your comments are not bringing literally anything to this issue, so I would ask to not interfere until you may bring something more helpful.

@cbuchner1 What kind of debug maybe be helpful for you? I have reinstalled drivers making sure that I have running 319 and 235 (not at once obviously) - drivers in this version provides support for optimus turning off intel one - but it is still segfaulting. I checked on another another computer with different NVIDIA optimus - and cudaminer works well there.

**Comment by marzhall** [comment]
Bluszcz says in issue #3 that he has solved this issue by re-installing his drivers. This should be closed.

**Comment by bluszcz** [comment]
Yes. The NVIDIA drivers they have "-optimus" switch which allows to install with the support for Optimus cards. Happy mining.
