### ISSUE TITLE
Make fails on ec2 instance with GRID K520

### ISSUE THREAD

**Issue by malford** [cbuchner1/CudaMiner#73]
Not sure if it is known already I am not able to build the most recent commit. and get this error: 

```
g++  -g -O2 -pthread -L/usr/local/cuda/lib64  -o cudaminer cudaminer-cpu-miner.o cudaminer-util.o cudaminer-sha2.o cudaminer-scrypt.o cudaminer-scrypt-jane.o salsa_kernel.o spinlock_kernel.o legacy_kernel.o fermi_kernel.o kepler_kernel.o test_kernel.o titan_kernel.o -L/usr/lib/x86_64-linux-gnu -lcurl -Wl,-Bsymbolic-functions -Wl,-z,relro compat/jansson/libjansson.a -lpthread  -lcudart -fopenmp
salsa_kernel.o: In function `validate_config(char*, int&, int&, KernelInterface**, cudaDeviceProp*)':
/home/ubuntu/CudaMiner/salsa_kernel.cu:131: undefined reference to `NV2Kernel::NV2Kernel()'
/home/ubuntu/CudaMiner/salsa_kernel.cu:130: undefined reference to `NVKernel::NVKernel()'
salsa_kernel.o: In function `find_optimal_blockcount(int, KernelInterface*&, bool&, int&)':
/home/ubuntu/CudaMiner/salsa_kernel.cu:346: undefined reference to `NV2Kernel::NV2Kernel()'
/home/ubuntu/CudaMiner/salsa_kernel.cu:344: undefined reference to `NVKernel::NVKernel()'
collect2: ld returned 1 exit status
make[2]: *** [cudaminer] Error 1
make[2]: Leaving directory `/home/ubuntu/CudaMiner'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/CudaMiner'
make: *** [all] Error 2
```

I can though build from this commit with out trouble: fba1561

**Comment by oholiab** [comment]
+1 on this, building on Ubuntu 13.10 and I get the same error

**Comment by oholiab** [comment]
Build is successful on 142261bb89144364873ab4c70772a96d16647966 (HEAD~3 at this point)

**Comment by techdragon** [comment]
Something in the commits after https://github.com/cbuchner1/CudaMiner/commit/142261bb89144364873ab4c70772a96d16647966 breaks this again as I had to roll back my repo after cloning from master and attempting to run the code.

**Comment by zerowind168** [comment]
Anyone has a solution to this error?

**Comment by cbuchner1** [comment]
Is everyone running ./autogen.sh before configure ?

2014/1/24 zerowind168 notifications@github.com

**Comment by cadwallion** [comment]
I had this same problem, and running `./autogen.sh` before `./configure` fixed this for me (after running `apt-get install automake`).

**Comment by zerowind168** [comment]
YES, THANK YOU. I have noted the authors notation.

On Thursday, January 30, 2014 4:20 AM, Andrew Nordman notifications@github.com wrote:

I had this same problem, and running ./autogen.sh before ./configure fixed this for me (after running apt-get install automake).

**Comment by minasami** [comment]
when i  ./autogen.sh
it gives me this error
autom4te: cannot open autom4te.cache/requests: Permission denied
aclocal: autom4te failed with exit status: 1
