### ISSUE TITLE
Performance on Visual Studio build?

### ISSUE THREAD

**Issue by VeliV** [cbuchner1/CudaMiner#85]
I've been trying to build this myself to get the latest good stuff, but when I build it in Visual Studio, I get only around 100khash/s. When using the cudaminer-2013.12.18 version with the binaries, I get about 350khash/s . Even when building the cudaminer-2013.12.18 from source, I get 1/3 of the khash I get with the build I make myself.

Is there something I am missing? Is this a problem with Visual Studio solution?

**Comment by cbuchner1** [comment]
A Debug vs. Release mode problem, maybe?

weird.

This weekend I will post some official binaries.

**Comment by VeliV** [comment]
I checked that, it's the performance is pretty identical. I dunno if there is a flag hidden somewhere that I need to change.

Ill do some test trying to compile it with minGW.

**Comment by VeliV** [comment]
I downloaded Visual Studio 2010 express and did a build with it's compilers from Visual Studio 2012. The performance matches the binaries you provided. 

I'll probably do some more tests with different Platform Toolsets, but at least now I can get to trying to add more algorithms to the miner :)

Thanks!
