### ISSUE TITLE
sha3, maxcoin not compiled nor linked in c173

### ISSUE THREAD

**Issue by zjunyi** [cbuchner1/CudaMiner#93]
sha3, maxcoin not compiled nor linked into cudaminer when pulled from git. can be done manually though.

**Comment by cbuchner1** [comment]
follow the instructions in the INSTALL file, then the compilation should
work without manual intervention

The reason for the problems is that I am updating the github repo from a
Windows PC, and from there I cannot update ./configure, Makefile.in etc..

2014-02-10 3:31 GMT+01:00 zjunyi notifications@github.com:

**Comment by zjunyi** [comment]
ah i see! i thought i read in the forum where you mentioned you obviated the need for autogen.sh. no issues then :D

**Comment by cbuchner1** [comment]
for major stable releases I tend to update ./configure etc from my Linux
box. But this maxcoin code is rather unstable

2014-02-10 9:48 GMT+01:00 zjunyi notifications@github.com:
