### ISSUE TITLE
Linux fails to build on 9eb44d0a24ec8e8ee381739cfd5c804bc3653637

### ISSUE THREAD

**Issue by ril3y** [cbuchner1/CudaMiner#94]
It appears that commenting out line 876 through 879 in cpu-miner.c allows for the program to compiler after that.  See below.

//case ALGO_KECCAK:
//      rc = scanhash_keccak(thr_id, work.data, work.target,
//                            max_nonce, &tv_start, &tv_end, &hashes_done);
//      break;

https://github.com/cbuchner1/CudaMiner/commit/9eb44d0a24ec8e8ee381739cfd5c804bc3653637

**Comment by cbuchner1** [comment]
and one more person who didn't run ./autogen.sh - see INSTALL file

2014-02-11 5:53 GMT+01:00 ril3y notifications@github.com:

**Comment by ril3y** [comment]
Doh!  thanks.  At least this way there will be some error terms for future idiots to google on!
Sorry.
