### ISSUE TITLE
build problems with keccak coins on Fedora 19

### ISSUE THREAD

**Issue by cinchcircuits** [cbuchner1/CudaMiner#97]
Unable to build on Fedora 19 without modifying code.

First, I needed to edit the produced Makefile and add a -lcrypto to the cudaminer_LDADD line.

After that, I am still not able to build with error messages about undefined references to scanhash_keccak 

Example:

g++  -g -O2 -pthread -L/usr/local/cuda/lib64  -o cudaminer cudaminer-cpu-miner.o cudaminer-util.o cudaminer-sha2.o cudaminer-scrypt.o cudaminer-scrypt-jane.o salsa_kernel.o sha256.o keccak.o fermi_kernel.o kepler_kernel.o test_kernel.o nv_kernel.o nv_kernel2.o titan_kernel.o -lcurl   compat/jansson/libjansson.a -lpthread  -lcudart -fopenmp -lcrypto 
cudaminer-cpu-miner.o: In function `miner_thread':
/home/mgregg/CudaMiner-2014-02-09/cpu-miner.c:877: undefined reference to`scanhash_keccak'
collect2: error: ld returned 1 exit status
make[2]: **\* [cudaminer] Error 1

Fortunately, I do not need coins, so one workaround is to comment out all the references to keccak coin in cpu-miner.c

After those two work-arounds I am able to build and mine scrypt and scrypt-jane coins fairly well.

I'll create these issues as separate tickets if desired.

**Comment by benmathia** [comment]
Just to add to this, I was having the same issues on Ubuntu 12.04, and those workarounds did it for me.

**Comment by cbuchner1** [comment]
following the procedure outlined in the INSTALL file would have fixed this
for you.

2014-02-16 21:06 GMT+01:00 Ben Oztalay notifications@github.com:

**Comment by benmathia** [comment]
Well, don't I feel silly. Followed the instructions, it worked no problems.

**Comment by cinchcircuits** [comment]
Well, running autogen.sh before configure as specified in the INSTALL file fixed my issue. 

Thank you for the reply.
